root: ./

redirects:  
    whereby-embedded-sdk-beta#ios-sdk: whereby-101/readme.md
    whereby-embedded-sdk-beta#android-sdk: whereby-101/readme.md
    whereby-embedded-sdk-beta#browser-sdk: whereby-101/readme.md
    
